/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.biz.analytics.checks;

import sirius.biz.analytics.scheduler.AnalyticsSchedulerExecutor;

/**
 * Provides the batch executor which is used as a bridge between the {@link sirius.biz.cluster.work.DistributedTasks}
 * framework and the schedulers of the checks framework.
 * <p>
 * This executor will be invoked for each scheduler and invokes the appropriate scheduler to create batches of entities
 * so be checked.
 *
 * @see SQLDailyCheckScheduler
 * @see SQLChangeCheckScheduler
 * @see MongoDailyCheckScheduler
 * @see MongoChangeCheckScheduler
 */
public class CheckSchedulerExecutor extends AnalyticsSchedulerExecutor {

    /**
     * Contains the queue used for distributed tasks generated by the checks framework.
     */
    public static final String QUEUE_CHECKS = "checks";

    @Override
    public String queueName() {
        return QUEUE_CHECKS;
    }

}
